version: '3.8'
services:
  spring-app:
    build:
      context: .
      dockerfile: spring.dockerfile
    container_name: spring-rest-api
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-15:5432/productdb
  postgres-db:
    image: 'postgres:15-alpine'
    restart: always
    container_name: postgres-15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=productdb
    ports:
      - '5433:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
volumes:
  db:
