server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  security:
    user:
      name: admin
      password: passw@rd

logging:
  level:
    org.springframework: info
    org.hibernate: info

snapadmin:
  enabled: true
  baseUrl: admin
  modelsPackage: com.brianeno.sample.entity

dbadmin:
  enabled: true
  baseUrl: admin
  modelsPackage: com.brianeno.sample.entity
  sqlConsoleEnabled: true